fix: correctly handle empty params
ory/go-acc pull request #36
Opened 2021-10-08 19:27 UTC by kubuzetto

2021-10-09 17:08 UTC, aeneasr requested changes
Could you please extract this logic into a separate func and add tests for it? That should resolve future regressions like the one introduced in the previous PR

2021-10-09 18:07 UTC, kubuzetto commented
Sure thing 👍 Where do your unit tests normally reside? I cannot locate them.

2021-10-10 15:59 UTC, aeneasr commented
We don't have them yet :( That's probably the root cause of missing the previous bug :) You can just add a new `cmd_test.go` and add the test there :)

2021-10-10 18:31 UTC, kubuzetto commented
Ah ok 😄 Added a simple test for `cmdBuilder`

2021-10-11 06:55 UTC, aeneasr approved these changes
Thank you!

2021-10-11 06:55 UTC, merged