fix: golang build 1.18 by upgrading dependency golang.org/x/sys
ory/go-acc pull request #41
Opened 2022-03-22 21:02 UTC by f-blass

Go build failed with go 1.18 with the following error:
 
```
# golang.org/x/sys/unix
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
../../pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.go:121:3: too many errors
```

2022-03-22 21:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/go-acc?pullRequest=41) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/go-acc?pullRequest=41) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/go-acc?pullRequest=41) it.</sub>

2022-03-23 08:35 UTC, f-blass commented
@aeneasr fyi

2022-03-23 09:08 UTC, aeneasr requested changes
Please make these changes only about upgrading the dependencies and remove the changes to cmd/root

2022-03-23 09:13 UTC, f-blass commented
Sorry, fixed.

2022-03-23 09:13 UTC, merged

2022-03-23 09:13 UTC, aeneasr commented
ty!

2022-03-23 10:48 UTC, f-blass commented
@aeneasr Could you please also tag a new version? Thank you!

2022-03-23 11:23 UTC, aeneasr commented
done